// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4YoonBNVeHFrKg86XeD1snu46uwxiT8',
    appId: '1:79093497311:web:3e55cb27ddcb3d0590986a',
    messagingSenderId: '79093497311',
    projectId: 'chatku-53120',
    authDomain: 'chatku-53120.firebaseapp.com',
    storageBucket: 'chatku-53120.appspot.com',
    measurementId: 'G-9FPYED4JS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-qqseKfclDW2txDKa4T-dSxoK6yC8VM',
    appId: '1:79093497311:android:988d145975172acf90986a',
    messagingSenderId: '79093497311',
    projectId: 'chatku-53120',
    storageBucket: 'chatku-53120.appspot.com',
  );
}
